apiVersion: apps/v1
kind: Deployment
metadata:   
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  name: rhtap-idk
spec:
  replicas: 1 
  template: 
    spec:
      containers:
      - image: quay.io/acmiel-rhtap/rhtap-idk:98e799f01884d93294669cca22e10fc38341f5bb@sha256:52185e0605d32d1bbfb688e885ed30522754994e796562f70f7a2909e821a804
        name: container-image  
