apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: rhtap-idk
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/acmiel-rhtap/rhtap-idk:7f5d30ede1be8c556f12a94b24c839bdc8c7b0a5@sha256:d2adc9508f460e83b9041f2e89264185d5ed572b1bb61cd91b77689fb0d449be
          name: container-image
